### ISSUE TITLE
Prettier checks failing on mobile styling

### ISSUE THREAD

**Issue by BRogers-BCIT** [Vero-Ventures/accubot#138]
After the commit to merge mobile styling on July 11th, prettier checks for the mobile-styling branch have been failing. The reason for this needs to be investigated and fixed before the branch can be merged into main.

**Comment by michaeleii** [comment]
Prettier checks just means that some files haven't been formatted correctly. Running `npm run format` should automatically format all files and a new commit should be made and pushed to the branch. I will see whats going on but should be simple to fix.
